import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Carousel from '../components/Carousel'
import DummyImage from '../public/footer-image.png'
import Image from 'next/image'
import Link from 'next/link'
import LinkedoutImage from '../public/linkedout.png'
import PrelovedImage from '../public/preloved.png'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />
        <meta name="theme-color" content="#ffffff" />
      </Head>
      <div className={ styles['home-header']}>
        <div className={styles['home-header__wrapper']}>
          <div className={styles['home-header__text']}>
            <div className={ styles['home-header__text-wrapper']}>
              <p>Hi👋 line one goes here</p>
              <p>Line two goes here</p>
              <p>Line three goes here and maybe longer</p>
            </div>
          </div>
          <div className={styles['home-header__visuals']}>
            <Image src={DummyImage} width={230} height={300} />
          </div>
        </div>
        <Carousel />
      </div>

      <div className={styles.projects}>
        <div className={styles['project-row']}>
          <div className={styles['project-imagewrapper']}>
            <Image src={ PrelovedImage} width={500} height={310} />
          </div>
          <div className={styles['project-textwrapper']}>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vehicula quis risus ut pharetra. Vivamus scelerisque lacus sed nibh venenatis viverra.</p>
            <ul className={styles['project-tags']}>
              <li>MongoDB</li>
              <li>React</li>
              <li>NodeJS</li>
              <li>CSS3/HTML5</li>
            </ul>
            <div className={styles['project-actions']}>
              <Link href="/" className="project-actions__repolink">See Repo</Link>
              <Link href="/" className="project-actions__livelink">Go Live</Link>
            </div>
          </div>
        </div>
        <div className={styles['project-row']}>
          <div className={styles['project-textwrapper']}>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vehicula quis risus ut pharetra. Vivamus scelerisque lacus sed nibh venenatis viverra.</p>
            <ul className={styles['project-tags']}>
              <li>MongoDB</li>
              <li>React</li>
              <li>NodeJS</li>
              <li>CSS3/HTML5</li>
            </ul>
            <div className={styles['project-actions']}>
              <Link href="/" className="project-actions__repolink">See Repo</Link>
              <Link href="/" className="project-actions__livelink">Go Live</Link>
            </div>
          </div>

          <div className={styles['project-imagewrapper']}>
            <Image src={ LinkedoutImage } width={500} height={280} />
          </div>
        </div>
      </div>

      {/* display shots */}

    </div>
  )
}
