import Head from 'next/head'
import Carousel from '../components/Carousel'
import Image from 'next/image'
import Link from 'next/link'
import DummyImage from '../public/footer-image.png'
import LinkedoutImage from '../public/linkedout.png'
import PrelovedImage from '../public/preloved.png'
import { createClient } from 'contentful'
import Shot from '../components/Shot'
import styles from '../styles/Home.module.scss'

export const getStaticProps = async () => {
  const client = createClient({
    space: process.env.NEXT_CONTENTFUL_SPACE_ID,
    accessToken: process.env.NEXT_CONTENTFUL_CDN_API
  })
  const res = await client.getEntries({ content_type: 'shot' })

  return {
    props: {
      shots: res.items,
    },
    revalidate: 1
  }
}

export default function Home({ shots }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />
        <meta name="theme-color" content="#ffffff" />
      </Head>
      <div className={ styles['home-header']}>
        <div className={styles['home-header__wrapper']}>
          <div className={styles['home-header__text']}>
            <div className={ styles['home-header__text-wrapper']}>
              <p>Hi👋 line one goes here</p>
              <p>Line two goes here</p>
              <p>Line three goes here and maybe longer</p>
            </div>
          </div>
          <div className={styles['home-header__visuals']}>
            <Image src={DummyImage} width={230} height={300} />
          </div>
        </div>
        <Carousel />
      </div>

      <div className={styles.projects}>
        <div className={styles['projects-description']}>
          <h3 id="#projects">Projects</h3>
        </div>
        <div className={styles['project-row']}>
          <div className={styles['project-imagewrapper']}>
            <Image src={ PrelovedImage} width={500} height={310} />
          </div>
          <div className={styles['project-textwrapper']}>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vehicula quis risus ut pharetra. Vivamus scelerisque lacus sed nibh venenatis viverra.</p>
            <ul className={styles['project-tags']}>
              <li>MongoDB</li>
              <li>React</li>
              <li>NodeJS</li>
              <li>CSS3/HTML5</li>
            </ul>
            <div className={styles['project-actions']}>
              <Link href="/" className="project-actions__repolink">See Repo</Link>
              <Link href="/" className="project-actions__livelink">Go Live</Link>
            </div>
          </div>
        </div>
        <div className={styles['project-row']}>
          <div className={styles['project-textwrapper']}>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vehicula quis risus ut pharetra. Vivamus scelerisque lacus sed nibh venenatis viverra.</p>
            <ul className={styles['project-tags']}>
              <li>MongoDB</li>
              <li>React</li>
              <li>NodeJS</li>
              <li>CSS3/HTML5</li>
            </ul>
            <div className={styles['project-actions']}>
              <Link href="/" className="project-actions__repolink">See Repo</Link>
              <Link href="/" className="project-actions__livelink">Go Live</Link>
            </div>
          </div>

          <div className={styles['project-imagewrapper']}>
            <Image src={ LinkedoutImage } width={500} height={280} />
          </div>
        </div>
      </div>

      <div className={styles['shots-container']}>
        <div className={styles['shots-summary']}>
          <h3 id="#shots">Practice Shots</h3>
          <p>I learn by making incremental steps, these are some of my smaller projects to help me build a solid foundation understanding of code flow, fundamental concepts and problem solving. </p>
        </div>
        <div className={styles['shots-wrapper']}>
          {shots.length > 0 && shots.map((shot, shotIndex) => (
            <Shot shot={shot} key={ shotIndex}/>
          ))}
        </div>
      </div>

    </div>
  )
}
