import Head from 'next/head'
import styles from '../styles/Home.module.scss'
import Carousel from '../components/Carousel'
export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5" />
        <meta name="msapplication-TileColor" content="#da532c" />
        <link rel="stylesheet" type="text/css" charset="UTF-8" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css" />
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css" />
        <meta name="theme-color" content="#ffffff" />
      </Head>
      <h1>Home</h1>
      <div className={ styles['carousel-header']}>
        <div className={styles['carousel-header__wrapper']}>
          <div className={styles['carousel-header__text']}></div>
          <div className={styles['carousel-header__visuals']}></div>
        </div>
        <Carousel />
      </div>
      {/* display all three projects */}

      {/* display shots */}

    </div>
  )
}
